inherit_from: .rubocop_todo.yml

Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Layout/AlignParameters:
  EnforcedStyle: 'with_fixed_indentation'

Style/EmptyMethod:
  EnforcedStyle: 'expanded'
